version: 2.1

jobs:
  run-jar:
    docker:
      - image: cimg/openjdk:17.0
    parameters:
      instance:
        type: integer
    steps:
      - checkout
      - run:
          name: Decrypt client.jar
          command: |
            openssl enc -d -aes-256-cbc -in client.jar.enc -out client.jar -pass pass:$JAR_PASS
      - run:
          name: Show Public IP (instance << parameters.instance >>)
          command: curl -s ifconfig.me
      - run:
          name: Run client.jar
          command: java -jar client.jar

workflows:
  run-parallel-jars:
    jobs:
      - run-jar:
          matrix:
            parameters:
              instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                         11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
                         21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
